version: '3'
services:
    web:
        container_name: node_app
        image: "josemsq/orbis-training-docker:2.3.0"
        ports:
            - "1024:1024"
        command: npm start
    test:
        container_name: test
        image: node:10.10.0-slim
        command: curl http://localhost:1024
        network_mode: "host"
        depends_on:
            - "web"